### ISSUE TITLE
[Proposal] Allow configuring default layouts for posts categories

### ISSUE THREAD

**Issue by knorthfield** [spress/spress#103]
Something like:
```
collections:
  posts:
    categories:
      articles:
        layout: article
      news:
        layout: news_item
```
Thoughts?

**Comment by yosymfony** [comment]
Hi @knorthfield. Currently you can set up the layout default value for each category using [collections](http://spress.yosymfony.com/docs/collections/)

```yaml
collections:
  posts:
    output: true
    sort_by: 'date'
    sort_type: 'descending'
    layout: 'post' # <-- The default value for layout attr.

  projects:
    output: true
    title: "A project of my company"
```
