### ISSUE TITLE
Custom From-matter doesn't work

### ISSUE THREAD

**Issue by enzolutions** [spress/Spress#32]
I tried the instructions provided in blog http://spress.yosymfony.com/docs/front-matter/

but using a from-matter like this

```
---
layout: default
image:
  feature: "assets/images/enzolutions_image_header.png"
  creditlink: "http://cr.linkedin.com/pub/werner-gomez/31/ba8/9b6"
  credit: "Yersika Ferreira"
---
```

The element page.image is null using twig debug.
