### ISSUE TITLE
Data sources

### ISSUE THREAD

**Issue by yosymfony** [spress/Spress#46]
Data sources can load data from certain locations like filesystem or database. Every data source must extends [`AbstractDataSource`](https://github.com/spress/Spress/blob/master/src/Core/DataSource/AbstractDataSource.php). Data loaded from data sources are called items. There is three type of them: content, layout and include. Items must implements [`ItemInterface`](https://github.com/spress/Spress/blob/master/src/Core/DataSource/ItemInterface.php).

**Type of items**:
* `content`: regular content like post or pages.
* `layout`: indicates how to organize the content.
* `include`: reusable content.

## FilesystemDataSource
Spress comes with [`FilesystemDataSource`](https://github.com/spress/Spress/blob/master/src/Core/DataSource/Filesystem/FilesystemDataSource.php) for loading your site (see #41 ). Data sources are defined at `data_source` option of the configuration file:

```yaml
data_sources:
  filesystem:
    class: 'Yosymfony\Spress\Core\DataSource\Filesystem\FilesystemDataSource'
    arguments:
      source_root: '%site_dir%/src'
      include: '%include%'
      exclude: '%exclude%'
      text_extensions: '%text_extensions%'
      attribute_syntax: '%attribute_syntax%'
```
This is the default configuration and is not necessary to modify your `config.yml` file at your site.

## Adds a custom data source from a plugin
Extends Spress with a new data source is straightforward:
* Suscribes to `spress.start` event and gets the `EnvironmentEvent` object received as an argument.
* Adds a custom data source: 

```php
$dsm = $environmentEvent->getDataSourceManager();
$dsm->addDataSource('dataSource-name', $yourDataSource);
```
## Adds a custom data source from the config.yml file
You can also adds your own data source using `config.yml` file of your site:

```yaml
data_sources:
  myCustomDataSource:
    class: 'Class\of\myCustomDataSource'
    arguments:
      argument1: "your value"
```
Note: if you want hold the filesystem data source don't forget appear that.
