### ISSUE TITLE
Preserve title from path filename

### ISSUE THREAD

**Issue by yosymfony** [spress/Spress#47]
Deals with #38.

In case of you want to preserve the title extracted from the filename path over the `title` attribute of *frontmatter* you can use `preserve_path_title`.

e.g: a post filename like: `2015-03-12-spress-is-a-static-site-generator.md`

```yaml
---
layout: post
title: Spress 静态网站生成器
preserve_path_title: true
categories: [Blog]
---
```
If you want set `preserve_path_title: true` as default for your posts you need add this attributes at your post collection: edit your `config.yml`:

```yaml
collections:
  posts:
    output: true
    preserve_path_title: true
```
