### ISSUE TITLE
add code test coverage to scrutinizer config

### ISSUE THREAD

**Issue by lury** [spress/Spress#52]
Hi,

if you add 
```
build:
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=codecoverage.xml'
                coverage:
                    file: 'codecoverage.xml'
                    format: 'php-clover'
```
at the end of scrutinizer config ( https://scrutinizer-ci.com/g/spress/Spress/settings/build-config ), you'd get code test coverage info.

You can see it on my fork on scrutinizer https://scrutinizer-ci.com/g/lury/Spress/code-structure/scrutinizer_fixes - there's an additional column with Test Coverage, and you can inspect coverage on the code level: https://scrutinizer-ci.com/g/lury/Spress/code-structure/scrutinizer_fixes/class/Yosymfony%5CSpress%5CCore%5CContentManager%5CPermalink%5CPermalinkGenerator ( you have to click "code coverage button above the code preview )
