### ISSUE TITLE
Taxonomy generator

### ISSUE THREAD

**Issue by yosymfony** [spress/Spress#57]
Taxonomy is a way to group things together. The taxonomy generator lets you group some items around a term. This generator **uses PaginatorGenerator** for generating multiple pages for each term.

## How to configure?
At frontmatter of the template page or its metadata file:

```yaml
 ---
 layout: default
 generator: taxonomy
 max_page: 5
 taxonomy_attribute: 'categories'
 permalink: '/:name'
 pagination_permalink: '/page:num'
 ---
```
* `max_page`: items per page (used by PaginationGenerator).
* `taxonomy_attribute`: The attribute name that contains the list of terms or taxons.
* `permalink`: permalink style for the taxonomy.
* `pagination_permalink': permalink style for multiples pages of a term.

Deals with #37
