### ISSUE TITLE
Items sorted at PaginationGenerator

### ISSUE THREAD

**Issue by yosymfony** [spress/Spress#61]
With this two new attributes: `sort_by` and `sort_type` you will be able to control how items are sorted at  `PaginationGenerator`. `sort_type` only supports `ascending` and `descending` values. Descending is the default behavior:

In the below example `date` value is the name of the attribute used as criteria for sorting:
```yaml
generator: pagination
provider: site.posts
max_page: 5
sort_by: date
```
Example with ascending order:
```yaml
generator: pagination
provider: site.posts
max_page: 5
sort_by: date
sort_type: ascending
```
Generator details at #45 .
Implementation: 268d3cc0e9e321f86b1d1fe140a530de144d4fcd
