### ISSUE TITLE
Sort items of a collection

### ISSUE THREAD

**Issue by yosymfony** [spress/Spress#67]
Items of a collection can be sorted with two new attributes with special meaning defined at the collection section of `config.yml` file of a Spress site
```yml
collections:
    posts:
        sort_by: 'date'
    projects:
        sort_by: 'title'
        sort_type: 'ascending'
```
* `sort_by`: the name of the attribute used as criteria to sort.
* `sort_type`: values accepted: `ascending` or `descending` that last one by default.

## Default values
Items of `posts` collection are sorted by descending `date` attribute.
Variables `site.categories` and `site.tags` are affected by posts sorting.

## Additional tasks
- [x] Update [`/docs/collections`](http://spress.yosymfony.com/docs/collections/) page.
- [x] Update default values section in [`/docs/configuration/`](http://spress.yosymfony.com/docs/configuration/) page.
- [x] Update Spress's lifecycle: [/docs/developers/spress-lifecycle](http://spress.yosymfony.com/docs/developers/spress-lifecycle).
 
Deals with issue #63
