### ISSUE TITLE
Map Converter for supporting .twig extension

### ISSUE THREAD

**Issue by yosymfony** [spress/Spress#73]
The `MirrorConverter` class has been replaced by `MapConverter` class. This new converter works like MirrorConverter but has an additional behaviour: to map configured filename's extensions to others. This new feature lets you work more appropriately with pages using IDEs such as PHPStorm.

e.g: a `index.twig` page will be compiled as `index.html`.

The default configuration:
```yaml
map_converter_extension:
  'html.twig': 'html'
  'twig.html': 'html'
  'twig': 'html'
```
## Additional tasks
* [x] Update [/docs/configuration](http://spress.yosymfony.com/docs/configuration) page.

Deals with issue #28
