### ISSUE TITLE
Allow default attributes on "pages" collection

### ISSUE THREAD

**Issue by yosymfony** [spress/Spress#93]
This feature let you setting up default attributes for all items belonging to `pages` collection. **Notice** that `pages` is the default collection and `layout` attribute is applied over CSS and JS files. To avoid that situation, feature #91 will be useful.

An example:

``` yaml
collections:
  pages:
    layout: default
  posts:
    sort_by: 'date'
    sort_type: 'descending'
```
