### ISSUE TITLE
Sorting 100+ files in one directory creates wrong sequencing

### ISSUE THREAD

**Issue by taylorren** [spress/Spress#99]
In `config.yml` file, I have modified as below:

```
collections:
  posts:
    output: true
    permalink: "/:path/:basename.html"
    sort_by: 'slug'
    sort_type: 'ascending'
```

Under `posts/` directory, I have created a sub-directory called `wesley` and it contains 100+ (131 to be exact) files: 0.toc.md, 001.md, 002.md, ..., 131.md. For each of these files, I created the header like this:

```
layout: "post"
title: "钻石花"
slug: "wesley-001"
book: 卫斯理全集
```

The above `001` will be corresponding to the deemed sequence of the output. In other words, the correct sequencing should be 0.toc, 001, 002, ...131. 

However, when the site is built, and I view the post list page, the first file in the sequence becomes `122.html`. After reaching `131.html`, it will display `0.toc.html` and 001 onwards till 121. 

I have other sub-directories under `posts` with similar slug naming convention but don't have this behavior. 

Don't know what is the problem for this. Please help.
